### PR TITLE
added support for remote/alternativ url

### PR DESCRIPTION
**Pull request by JasonMask**
not that i would pretend that i knew what i did there but i did what i could and you might concider having a look on it ;)

[edit]this would satify my needs for #887[/edit]

thx for your work anyway

cu jason

### CODE REVIEW

**Comment by klassm** [comment]
Hi Jason,

hm well generally this looks good to me. The only thing I am not fancy about is naming:

Before your pull request there was only one URL - called URL. 

Now we got a URL (called URL with a description of http://192.168..... and so on) and a remote URL for dynDNS. This does not really make clear what happens because when users only have a remote URL, they might enter it only in the second field. Well, this works but not the way you expected it to do.

Maybe you could change the naming to URL (for the first URL) and an alternative URL. I would even fancy some description on when the alternative URL will be used.

Matthias

**Comment by JasonMask** [comment]
hi matthias,

i don´t stick to the naming so i´ll try to change it as suggested.

regarding the the details on when the alternative url is used: do you have a place where i should document the behaviour. i just can´t think of a phrase that would be short enough to fit the form field.

right now the alternativ url is used for a retry when a call to the default url fails. if this retry succeeds the following calls will use the alternativ url for the next calls. If these calls to the alternativ url do fail, it will retry the original default url and keep using this...
if both fail, you´ll get the known error...

any idears on how to shorten it down? oh and maybe it should metion my original reason to add this function so that people might understand why we are doing this ^^

anyhow i´ll do that "alternativ url" changes later today. feel free to do what ever changes you want to my code. I won´t be mad anyway

cu jason

**Comment by JasonMask** [comment]
hi matthias,

i finally found the time to apply the requested changes.
hope this helps you and the app
as you might have noticed my time is pretty limited so i´ll leave everything else to you.

cu jason

**Comment by klassm** [comment]
Hi Jason,

first of all - thanks for your contribution. I just merged the pull request. However let me make some comments on your code:

* Putting logic in getters is really considered bad practice. Effectively, Java community discussed that issue all the time - but in effect getters are more or less only public properties, giving frameworks the ability to use the Java Bean Convention to use reflection. Whenever I see a Getter, I won't expect it to contain logic.
* FHEMWEBConnection is effectively a singleton. For sure, it contains an attribute for the server spec. However, that property may not change during multiple requests. Connection retries may happen concurrently, breaking your global attributes approach. I replaced that logic by some simple parameters (and cleaned up my own messy FHEMWEB connection code ...). This also applies to your toggleUrl method in FhemServerSpec.

And some more things I added:
* The detail view got an extra text view on why one would use the secondary URL field. I don't yet know whether the text is "good enough" - but it's a start.
* The detail fragment enforces the URL to start with http
* The new instrumentation tests also check the secondary URL field

The changes will be included in 3.4.6.

Thanks again,
Matthias

**Pull request merged**
