### PR TITLE
Add initial support for plotReplace and fixedrange

### PR DESCRIPTION
**Pull request by stephanritscher**
This pull request is a suggestion how to handle #1341 and #1343:

### plotReplace
- Read and parse plotReplace attribute of SVG devices
- Replace %key% by respective value in get command (replacement before input processing)

Disclaimer
- No evaluation of perl expressions in {}
- No treatment of <key> (replacement after input processing) [I'm not sure whether this is relevant for andFHEM]
- No treatment of special variables $data{min1} etc. (only relevant for <key> replacement)

### fixedrange
- Read and parse fixedrange attribute of SVG devices
- Set default startDate and endDate based on fixedrange value
- Supported fixedrange values: <range> [offset]
  where range is one of hour, <N>hours, day, <N>days, week, <N>weeks, month, <N>months, year, <N>years
  and offset is an integer.
- Calculation of startDate and endDate behaves basically as if endPlotNow was set to 1

Disclaimer:
- No support for fixed dates (in the form YYYY-MM-DD)
- endPlotNow and endPlotToday are not evaluated

### CODE REVIEW

**Comment by klassm** [comment]
Thanks for those commits. I'll have a look at those next weekend. Just one question: would it make sense to add some unit tests for that functionality? I find it kind of hard to maintain code without breaking it when not having any tests -.-
Thanks again for your time and this pull request!
Matthias

**Comment by stephanritscher** [comment]
Sure, I'll give it a try.

**Comment by klassm** [comment]
Looks good to me. I guess you tried it out locally on your machine, so I'll just merge it. There's some minor stuff to do, but I'll just do that after the merge.
Thanks for the PR!

**Comment by klassm** [comment]
Minor cleanup work is done (https://github.com/klassm/andFHEM/commit/b28860330a9c5144934bfc5d825bfee904768b3f) - I hope everything still works, I relied on your tests :D.

Beta release is currently running. Will be done in a minute or so.

**Pull request merged**
